name: Run Colab Notebook

on:
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Colab Notebook
      uses: machine-learning-apps/Run-Colab-Notebook@master
      with:
        colab-notebook-url: 'https://colab.research.google.com/github/serchmaa/repositoryforjavzaa/colabforjavzaa.ipynb'
        colab-token: ${{ secrets.REFRESH_TOKEN }}
