name: Minimal Workflow Test

on:
  schedule:
    - cron: '*/1 * * * *'  # Every 30 minutes
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print message
      run: echo "Minimal workflow syntax is correct."
